import "./App.css";
import Footer from "./Footer";
import Outro from "./Outro";
import Questions from "./Questions";
import Intro from "./Intro";
import HumanRight from "./HumanRight";
import CurrentExpressions from "./CurrentExpressions";
import Toolkit from "./Toolkit";
import HybridTheory from "./HybridTheory";
import ExtendIt from "./ExtendIt";

const App = () => {
  
  return (
    <div className="layout">
      <header className="navbar">
        <div className="container columns">
          <div className="logo">
            <a href="https://expressionsofpeace.org">Expressions of Peace</a>
          </div>
        </div>
      </header>

      <section className="expressions centeed">
        <Intro />
        <HumanRight />

        <ExtendIt />
        <hr></hr>
        <h2
          style={{
            fontSize: "2rem",
            marginTop: "60px",
            marginBottom: "60px",
            lineHeight: "2.4rem",
          }}
        >
          Individual Sovereignity via Peace-oriented Diplomacy
        </h2>
   

        <p
          style={{
            marginLeft: "8%",
            marginRight: "8%",
            color: "black",
         
            textAlign: "center",
            fontSize: "1.6rem",
          }}
        >
          <span
            style={{
              backgroundColor: "yellow",
              color: "black",
              paddingLeft: "4px",
              paddingRight: "4px",
            }}
          >
            <i>
              It's an experience, that is priceless; more about being, than
              having.
            </i>
            <br></br> <br></br>
          </span>{" "}
          <br></br>
          As a proof of concept; a decentralized app launched on Ethereum
          blockchain's{" "}
          <a
            href="https://blog.logrocket.com/mainnet-vs-testnet-environments-explained/"
            target={"_blank"}
            rel="noreferrer"
          >
            <u>test networks.</u>
          </a>{" "}
        </p>

        <div className="centered">
          <h1
            style={{
              textAlign: "center",
              marginTop: "2rem",
              fontSize: "2.2rem",
              marginBottom: "2rem",
            }}
          >
            ? you may wonder;
          </h1>

        </div>

        <div className="questions">
        <Questions />

        </div>
        <br></br>
        <br></br>
        <hr></hr>
        <br></br>
        <br></br>
        <div className="">
          <CurrentExpressions />
          <Toolkit />
        </div>

        <br></br>
        <br></br>
        <hr></hr>
       
        <div className="centered">
        
        </div>
        <br></br>
        <br></br>
        <hr></hr>

        <p
          style={{
            fontSize: "1.6rem",
            marginTop: "40px",
            paddingLeft: "10%",
            paddingRight: "10%",
          }}
        >
          <HybridTheory />
          {/* Tokenomics design of the incentivisation is still a work in progress
            however, to start with, following tokens/coins imagined to be viable
            on variety of main networks as NFT and Escrow contracts deployed to:{" "}
            <strong> $Peace, $Green, $Wisdom, $Honesty and $Respect</strong>
            <br></br>
            <br></br>
            Below is the initial incentive design{" "}
            <a
              href="https://miro.com/app/board/uXjVOX94E5k=/?share_link_id=677735435690"
              target={"_blank"}
              rel="noreferrer"
              style={{ backgroundColor: "black", color: "white" }}
            >
              {" "}
              imagined,{" "}
            </a>
            and{" "}
            <a
              href="https://github.com/demo-verse/expressions-metadata-standard"
              target={"_blank"}
              rel="noreferrer"
              style={{ backgroundColor: "red", color: "white" }}
            >
              {" "}
              here{" "}
            </a>
            is the metadata standard for NFTs generated by expressions, that
            would accumulate acknowledgements, attestations and recognitions by
            the respective participants, in space-time. */}
          {/* <h3 style={{ lineHeight: "2.4rem", fontSize: "2.2rem" }}>
              Not a matter of legitimacy, but time.
            </h3>
            <br></br>
          We truly believe that Peace should not be brought up as a resolution
            of voting or people given environment or processes, where they
            hesitate on generosity, exclude one another, by the separation,
            biases inherited, since ages. */}
          {/* <ProcessReasoning /> */}
          <br></br>
          <br></br>

          <hr></hr>
          <br></br>
          <Outro />
          <img
        alt="YinYang symbol"
        src="YinYang.png"
        width={"22%"}
      ></img>
      
     
        </p>
        <hr></hr>

        <br></br>
        <br></br>
        <div className="express-yourself">
          {/* Our Dance - Wax Tailor ft. Charlotte Savary */}
          <iframe
            width="80%"
            height="640"
            src="https://www.youtube.com/embed/-QtqhPR7d0I"
            title="YouTube video player"
            frameBorder="0"
            allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
            allowFullScreen
          ></iframe>
        </div>
      </section>
<br></br><br></br>

      <Footer />
    </div>
  );
};

export default App;
